!               **************************
                MODULE DECLARATIONS_KHIONE
!               **************************
!
!***********************************************************************
! KHIONE   V8P0                                             02/11/2016
!***********************************************************************
!
!brief    DECLARATION OF PRINCIPAL KHIONE VARIABLES
!
!history  F. HUANG (CLARKSON U.) AND S.E. BOURBAN (HRW)
!+        11/11/2016
!+        V7P3
!+        Coupling TELEMAC-2D with KHIONE (ice modelling component)
!+        Initial developments
!
!history  R.ATA
!+        03/09/2018
!+        V8P0
!+        Merge of DECLAATIONS_ICE2D
!
!history  F.SOUILLE (EDF)
!+        30/09/2019
!+        V8P0
!+        Added new variables
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF_DEF
!
!       NOTE: THIS MODULE IS ORGANIZED IN 6 PARTS
!
!       (1) VECTORS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
!       (2) INTEGERS
!       (3) LOGICAL VALUES
!       (4) REALS
!       (5) STRINGS
!       (6) ALIASES (IF NECESSARY)
!
!
!=======================================================================
!
!  STRUCTURE USED FOR WRITTING OUT THE TIME SERIES FILE
!
!-----------------------------------------------------------------------
!
      TYPE STR_CELL_TYPE
        INTEGER :: NVAL
        CHARACTER(LEN=24), ALLOCATABLE :: TXT(:)
        CHARACTER(LEN=24), ALLOCATABLE :: UNT(:)
        CHARACTER(LEN=24), ALLOCATABLE :: VAL(:)
      END TYPE STR_CELL_TYPE
!
      TYPE STR_LINE_TYPE
        INTEGER :: NVAL
        CHARACTER(LEN=24) :: HTXT
        CHARACTER(LEN=24) :: HUNT
        CHARACTER(LEN=24) :: HVAL
        TYPE (STR_CELL_TYPE), ALLOCATABLE :: CELLS(:)
      END TYPE STR_LINE_TYPE
!
!=======================================================================
!
!       0) PARAMETERS
!
!-----------------------------------------------------------------------
!
!     MAXIMUM NUMBER OF VALUES OF KEY-WORDS OF ONE KIND
!       (INTEGER, LOGICAL, ETC.)
!
      INTEGER, PARAMETER :: MAXKEY = 300
!
!
!=======================================================================
!
!       1) OUTPUTS
!
!-----------------------------------------------------------------------
!
!     VARIABLES FOR GRAPHIC PRINTOUT
!
      CHARACTER(LEN=72) VARDES,VARIMP
!
!     GRAPHIC PRINTOUT PERIOD KHIONE
!
      INTEGER LEOPRD
!
!     LISTING PRINTOUT PERIOD KHIONE
!
      INTEGER LISPRD
!
!     MAXIMUM NUMBER OF OUTPUT VARIABLES
!
      INTEGER, PARAMETER :: MAXVAR = 50
!
!     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!
      LOGICAL SORLEO(MAXVAR),SORIMP(MAXVAR)
!
!     BLOCK OF VARIABLES FOR OUTPUT
!
      TYPE(BIEF_OBJ), TARGET :: VARSOR
!
!     NAMES AND UNITS OF VARIABLES
!       ( THESE TWO ARE SET IN LECDON_, THROUGH A CALL TO NOMVAR_ )
      CHARACTER(LEN=32) TEXTE(MAXVAR),TEXTPR(MAXVAR)
!
!     VARSOR FILTER FOR CONTINUED COMPUTATION
!
      INTEGER :: ALIRE(MAXVAR)
!     BE ABSOLUTLY SURE THAT ALIRE IS SIZE MAXVAR
      PARAMETER ( ALIRE = (/
!         1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,
     &    0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
     &    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /) )
!
!     TITLE OF STUDY
!
      CHARACTER(LEN=72) TITICECAS
!
!     FOR TIME SERIES OUTPUT
!
      TYPE (STR_LINE_TYPE) :: LINES
!
!=======================================================================
!
!      2) FILES
!
!-----------------------------------------------------------------------
!
!
!     MAXIMUM RANK OF LOGICAL UNITS (OPENING FILES) AS DECLARED IN
!     SUBMIT STRINGS IN THE DICTIONARY
!
      INTEGER, PARAMETER :: MAXLU_ICE = 14
!
!     TELEMAC-2D FILES
!
      TYPE(BIEF_FILE) :: ICE_FILES(MAXLU_ICE)
!
!     KHIONE RESULT FILE NUMBER
!
      INTEGER ICERES
!
!     KHIONE BOUNDARY CONDIITON FILE NUMBER
!
      INTEGER ICECLI
!
!     KHIONE GEOMETRY FILE NUMBER
!
      INTEGER ICEGEO
!
!     KHIONE STEERING FILE NUMBER
!
      INTEGER ICECAS
!
!     KHIONE REFERENCE FILE NUMBER
!
      INTEGER ICEREF
!
!     KHIONE PREVIOUS ICE COVER FILE NUMBER (EULERIAN)
!
      INTEGER ICECOV
!
!     KHIONE PREVIOUS ICE PACKS FILE NUMBER (LAGRANGIAN)
!
      INTEGER ICEBLK
!
!     KHIONE CLOGGING ICE RESULTS FILE NUMBER
!
      INTEGER CLGRFO
!
!=======================================================================
!
!      3) DICTIONARY
!
!-----------------------------------------------------------------------
!
!     COPY OF SUBMIT STRINGS IN THE DICTIONARY
!
      CHARACTER(LEN=PATH_LEN) SUBMIT(4,300)
!
!
!=======================================================================
!
!       4) ALGORITHMIC DIFFERENTIATION
!
!-----------------------------------------------------------------------
!
!
!     NUMBER OF DIFFERENTIATING ARRAYS, AND THOSE WITH A GIVEN NAME
!
      INTEGER NADVAR,N_NAMES_ADVAR
!
!     NAMES OF DIFFERENTING ARRAYS (GIVEN BY USER)
!
      CHARACTER(LEN=32) NAMES_ADVAR(MAXVAR)
!
!     BLOCK OF DIFFERENTIATED VECTORS
!
      TYPE(BIEF_OBJ), TARGET :: ADVAR
!
!
!=======================================================================
!
!       5) SWITCHES AND OPTIONS
!
!-----------------------------------------------------------------------
!
!     NUMBER OF DIFFERENTIATING ARRAYS, AND THOSE WITH A GIVEN NAME
!
      INTEGER NICVAR,N_NAMES_ICVAR
!
!     ICE PROCESSES INCLUDE:
!     - 2: HEAT EXCHANGE
!     - 3: ICE COVER IMPACT
!     - 5: CLOGGING
!     - 7: STATIC BORDER ICE
!
      INTEGER ICEPROCESS
!
!     NUMBER OF TRACERS ADDED WHEN USING ICEPROCESS
      INTEGER  ICETR
!
!     DEBUGGER
      INTEGER DEBUG
!
!     FRAZIL CONCENTRATION
      INTEGER IND_F
!
!     WATER TEMPERATURE (DUPLICATED INDEX)
      INTEGER IND_T
!
!     SALINITY (DUPLICATED INDEX)
      INTEGER IND_S
!
!=======================================================================
!
!       1) HEAT FLUXES
!
!-----------------------------------------------------------------------
!
!     THERMAL BUDGET: NET SUM OF ALL THERMAL FLUXES
      TYPE(BIEF_OBJ), TARGET :: SUMPH
!
!     THERMAL BUDGET: SOLAR RADIATION UNDER CLEAR SKY
      TYPE(BIEF_OBJ), TARGET :: PHCL
!
!     THERMAL BUDGET: SOLAR RADIATION UNDER CLOUDY SKY
      TYPE(BIEF_OBJ), TARGET :: PHRI
!
!     THERMAL BUDGET: NET SOLAR RADIATION AFTER REFLECTION
      TYPE(BIEF_OBJ), TARGET :: PHPS
!
!     THERMAL BUDGET: EFFECTIVE BACK RADIATION
      TYPE(BIEF_OBJ), TARGET :: PHIB
!
!     THERMAL BUDGET: EVAPORATION HEAT FLUX
      TYPE(BIEF_OBJ), TARGET :: PHIE
!
!     THERMAL BUDGET: CONDUCTIVITY HEAT FLUX
      TYPE(BIEF_OBJ), TARGET :: PHIH
!
!     THERMAL BUDGET: PRECIPITATION
      TYPE(BIEF_OBJ), TARGET :: PHIP
!
!     THERMAL BUDGET: HEAT TRANSFER BETWEEN WATER AND ICE
      TYPE(BIEF_OBJ), TARGET :: PHIW
!
!     WATER DEPTH
      TYPE(BIEF_OBJ), TARGET :: HTW
!
!     WATER TEMPERATURE
!      TYPE(BIEF_OBJ), TARGET :: TW
!
!     HEAT TRANSFER COEFFICIENT BETWEEN SURFACE ICE AND WATER
!      TYPE(BIEF_OBJ), TARGET :: HWIN
!      DOUBLE PRECISION HWIN
!
!     WATER SURFACE ELEVATION
      TYPE(BIEF_OBJ), TARGET :: ETA
!
!     ELEVATION OF THE BOTTOM OF ICE
      TYPE(BIEF_OBJ), TARGET :: ETAB
!
!
!=======================================================================
!
!       2) PHYSICAL PROPERTIES AND CONSTANTS
!
!-----------------------------------------------------------------------
!
!     ICE EXPANDS UPON FREEZING, WHICH IS THE OPPOSITE OF MOST OTHER
!       SUBSTANCES. AT 0[oC] IT HAS A DENSITY OF 916.8[kg/m3] AS
!       COMPARED TO A DENSITY OF 999.8[kg/m3] FOR WATER AT THE SAME
!       TEMPERATURE. AS A RESULT, ICE FLOATS IN WATER.
!     NOTE: THE MAXIMUM WATER DENSITY IS 1000[kg/m3] AT 4[oC]
!
!     ICE DENSITY ( DEFAULT = 916.8 kg/m3 )
      DOUBLE PRECISION  RHO_ICE
!###>         KNOWN AS  RHOICE
!
!     AIR DENSITY ( DEFAULT = 1.225 kg/m3 )
      DOUBLE PRECISION  RHO_AIR
!###>         KNOWN AS  RHOAIR
!
!     WATER DENSITY
!     -> ROEAU IS IN DECLARATIONS_TELEMAC2D
!     -> RO0 IS IN DECLARATIONS_TELEMAC3D AND IN WAQTEL
!      DOUBLE PRECISION  RHO_EAU
!
!     SPECIFIC HEAT OF WATER (DEFAULT = 4.1855 kJ/kgK )
!       (HEAT PRODUCED WHILE WATER SOLIDIFY AT CONSTANT TEMPERATURE)
!     -> CP_EAU IS IN DECLARATIONS_WAQTEL
!      DOUBLE PRECISION  CP_EAU
!
!     SPECIFIC HEAT OF ICE (DEFAULT = 2.04 kJ/kgK ), or 2.108 ?
!       (HEAT PRODUCED WHILE ICE ??? AT CONSTANT TEMPERATURE)
      DOUBLE PRECISION  CP_ICE
!
!     LATENT HEAT OF ICE (DEFAULT = 334. kJ/kgK )
!       (HEAT PRODUCED WHILE ICE MELT AT CONSTANT TEMPERATURE)
      DOUBLE PRECISION  LH_ICE
!###>         KNOWN AS  XLATEN
!
!
!     CONSTANT, COEFFICIENT FOR LINEARIZED HEAT FLUX EXCHANGES
!     .. BETWEEN WATER AND AIR
      DOUBLE PRECISION  CST_WATAIR,LIN_WATAIR
!###>         KNOWN AS  ALP,       HWA
!     .. BETWEEN ICE AND AIR
      DOUBLE PRECISION  CST_ICEAIR,LIN_ICEAIR
!###>         KNOWN AS  APLW,      HIA
!
!      BOLTZMANN CONSTANT (WM-2K-4)
!     -> BOLTZ IS IN DECLARATIONS_WAQTEL
!       DOUBLE PRECISION SGMA
!
!     COEFFICIENT FOR BACK RADIATION HEAT FLUX
      DOUBLE PRECISION COEF_PHIB
!
!     COEFFICIENT FOR EVAPORATION HEAT FLUX
      DOUBLE PRECISION COEF_PHIE
!
!     COEFFICIENT FOR CONDUCTIVE HEAT FLUX
      DOUBLE PRECISION COEF_PHIH
!
!     COEFFICIENT FOR PRECIPITATION HEAT FLUX
      DOUBLE PRECISION COEF_PHIP
!
!     SOLAR CONSTANT (W/M^2)
      DOUBLE PRECISION SIO
!
!     ALBEDO OF ICE
      DOUBLE PRECISION ALBE
!
!
!=======================================================================
!
!       ?) GEOGRAPHICAL CONSIDERATIONS
!
!     TODO: TO BE REPLACED BY A COMPUTATION FROM PHI0 (AND LAMBD0)
!
!     STANDARD LONGITUDE, IN DEG REES
      DOUBLE PRECISION ALSM
!
!     LOCAL LONGITUDE, IN  DEGREES
      DOUBLE PRECISION ALLM
!
!     -1, FOR WEST LONGITUDE; + FOR EAST LONGITUDE
      DOUBLE PRECISION ETADIR
!
!
!
!=======================================================================
!
!       ?) FREEZE-UP RELATED PARAMETERS
!
!     LENGTH OF A-AXIS OF A FRAZIL CRYSTAL [ M ]
      DOUBLE PRECISION DF
!
!     FRAZIL CRYSTAL THICKNESS [ M ]
      DOUBLE PRECISION DE
!
!     WATER-FRAZIL THERMAL CONDUCTIVITY [ W/M/oC ]
      DOUBLE PRECISION TC_WT                        !  =>  REPLACES XKWP

!     THERMAL CONDUCTIVITY OF BLACK ICE ( W/M/oC )
      DOUBLE PRECISION TC_BI                        !  =>  REPLACES XKI

!     THERMAL CONDUCTIVITY OF WHITE ICE ( W/M/oC )
      DOUBLE PRECISION TC_WI                        !  =>  REPLACES XKW

!     THERMAL CONDUCTIVITY OF SNOW ( W/M/oC )
      DOUBLE PRECISION TC_S                         !  =>  REPLACES XKS
!
!     SETTLING COEFFICIENT OF FRAZIL ON BARS
      DOUBLE PRECISION AF
!
!     NUSSELT NUMBER
      DOUBLE PRECISION VNU
!
!     POROSITY OF SURFACE ICE
      DOUBLE PRECISION SURF_EF
!
!     INITIAL SUSPENDED FRAZIL CONCENTRATION
      DOUBLE PRECISION CV0
!
!     INITIAL ICE THICKNESS
      DOUBLE PRECISION THI0
!
!     MAXIMUM ICE CONCENTRATION
      DOUBLE PRECISION ANMAX
!
!     DARCY'S COEFFICIENT FOR SEEPAGE FLOW IN RUBBLE ICE
      DOUBLE PRECISION DARCYRUB
!
!     DARCY'S COEFFICIENT FOR SEEPAGE FLOW IN ICE ISLANDS
      DOUBLE PRECISION  DARCYILD
!
!     PROBABILITY OF DEPOSITION OF FRAZIL PARTICLES REACHING THE
!       SURFACE LAYER - OPEN WATER
      TYPE(BIEF_OBJ), TARGET :: THETA0
!
!     PROBABILITY OF DEPOSITION OF FRAZIL PARTICLES REACHING THE
!       SURFACE LAYER - ICE
      TYPE(BIEF_OBJ), TARGET :: THETA1
!
!     COEFFICIENT QUANTIFYING THE RATE OF REENTRAINMENT OF SURFACE
!       ICE PER UNIT AREA
      TYPE(BIEF_OBJ), TARGET :: BETA1
!
!     AVERAGE RISING VELOCITY OF FRAZIL ICE IN THE TURBULENT RIVER FLOW
      TYPE(BIEF_OBJ), TARGET :: VBB
!
!     ICE CONCENTRATION AS COMPUTED FROM SURFACE ICE PARTICLES
!     (ALSO USED TO DEFINE OPEN WATER VS. UNDER ICE COVER)
      TYPE(BIEF_OBJ), TARGET :: ANFEM
!
!     TOTAL ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: THIFEM
!
!     SOLID ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: THIFEMS
!
!     FRAZIL ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: THIFEMF
!
!     DYNAMIC ICE GROWTH AREA AS A FRACTION OF THE NODE AREA
      TYPE(BIEF_OBJ), TARGET :: DWB
!
!     UNDERCOVER ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: HUN
!
!     FREEZING POINT OF WATER ( 0.oC BY DEFAULT )
      DOUBLE PRECISION CST_TMELT
      TYPE(BIEF_OBJ), TARGET :: TMELT
!
!=======================================================================
!
!       ?) ICE COVER RELATED PARAMETERS
!
!
!     INITIAL SURFACE ICE CONCENTRATION
      DOUBLE PRECISION CA0
!
!     ICE VELOCITY COMPONENTS
      TYPE(BIEF_OBJ), TARGET :: U_ICE,V_ICE
!
!     EQUIVALENT ICE HEIGHT
      TYPE(BIEF_OBJ), TARGET :: H_ICE
!
!     ICE SHEAR STRESS ON THE FLOW
      TYPE(BIEF_OBJ), TARGET :: TIWX,TIWY
!
!     ICE FRICTION
      TYPE(BIEF_OBJ), TARGET :: ICESTR
!
!     WATER + ICE COVER GRADIENTS        /!\ CAN DO WITHOUT BEING GLOBAL
      TYPE(BIEF_OBJ), TARGET :: DCOVX,DCOVY

!     TURBULENT INTENSITY
      TYPE(BIEF_OBJ), TARGET :: VZ
!
!     CRITICAL WATER TEMPERATURE FOR BORDER ICE
      TYPE(BIEF_OBJ), TARGET :: TCR
!
!     CRITICAL VELOCITY ABOVE WHICH STATIC BORDER ICE WILL NOT FORM
      DOUBLE PRECISION VCRBOR
!
!     CRITICAL VELOCITY ABOVE WHICH DYNAMIC BORDER ICE WILL NOT FORM
      DOUBLE PRECISION VCRBOM
!
!     INITIAL CONCENTRATION FOR BORDER / SKIM ICE FORMATION
      DOUBLE PRECISION ANFEM0      ! REPLACES ANMAXBORDER AND ANMAXSKIM
!
!     LAW OF FRICTION ON UNDER ICE COVER
      INTEGER IFROT
!
!     LAW FOR FRICTION COEFFICIENT
      INTEGER IFICE
!
!     FRICTION COEFFICIENT OF THE UNDER ICE COVER
      DOUBLE PRECISION FICE

!     MAX FRICTION COEFFICIENT OF THE UNDER ICE COVER
      DOUBLE PRECISION FICE_MAX
!
!     EQUIVALENT SURFACE ICE THCIKNESS (LAW FOR FRICTION COEFFICIENT=1)
      DOUBLE PRECISION THIE
!
!
!=======================================================================
!
!       ?) CLOGGING RELATED PARAMETERS
!
!     POROSITY OF ACCUMULATED ICE
      DOUBLE PRECISION CLOG_EF
!
!     ANGLE OF ACCUMULATED ICE
      DOUBLE PRECISION CLOG_THETA
!
!     PHYSICAL CHARACTERISTICS OF THE INTAKE RACK
      DOUBLE PRECISION CLOG_VDIST,CLOG_VDIAM,CLOG_TDIST,CLOG_TDIAM
!
!     CLOGGED BOUNDARY NUMBERS
      INTEGER NFRCLOG
      INTEGER, ALLOCATABLE :: NUMCLOG(:)
!
!     GROWTH THICKNESS OF THE VERTICAL AND HORIZONTAL ACCRECION
      DOUBLE PRECISION, ALLOCATABLE :: CLOG_VWDTH(:),CLOG_TWDTH(:)
!
!     PHYSICAL SIZE OF LENGTHS OF THE VERTICAL AND HORIZONTAL BARS
      DOUBLE PRECISION, ALLOCATABLE :: CLOG_VLGTH(:),CLOG_TLGTH(:)
!
!     TOTAL VOLUM OF ACCRECION
      DOUBLE PRECISION, ALLOCATABLE :: CLOG_VOLUM(:)
!
!
!=======================================================================
!
!       ?) ICE CHARACTERISATION
!
!     REPLACEMENT OF:
!       ICE ISLAND INDEX:   TYPE(BIEF_OBJ), TARGET :: JAMFEM
!       BORDER ICE INDEX:   TYPE(BIEF_OBJ), TARGET :: ISBORDER
!       ICE TYPE INDEX:     TYPE(BIEF_OBJ), TARGET :: ICEREGION
!     BY ONE MAP OF INTEGERS
!       (PRIMARY NUMBERS FOR COMBINED CHARACTERISATIONS)
!       1 - OPEN WATER
!       2 - BOUNDARY NODE
!       3 - STATIC BORDER ICE, FULLY WITHIN THE BORDER ICE COVER
!       5 - STATIC BORDER ICE ON THE EDGE OF THE BORDER ICE COVER
!       7 - STATIC BORDER ICE THAT HAS GROWN A SUFFICIENTLY THICK COVER
!     WHICH MAKE THE FOLLOWING COMBINATIONS:
!       6 - BORDER ICE NODE ALSO ON THE DOMAIN BOUNDARY
!      15 - ON THE EDGE OF THE BORDER ICE COVER
!      30 - AS 15 BUT ALSO ON THE DOMAIN BOUNDARY
!     NOTE THAT 5 CANNOT BE ON ITS OWN, AND THEREFORE 10 IS NOT USED.
      TYPE(BIEF_OBJ), TARGET :: ICETYPE
!
!     INTEGERS WORKING ARRAYS
      TYPE(BIEF_OBJ), TARGET :: IT1,IT2
!
!-----------------------------------------------------------------------
!     NUMBER OF PARCELS IN EACH ELEMENT
      TYPE(BIEF_OBJ), TARGET :: NPARSINEL
!     NUMBER OF PARCELS FOR EACH FINITE ELEMENT NODE
      TYPE(BIEF_OBJ), TARGET :: NPARSONOD
!
!     COEFFICIENT QUANTIFYING THE RATE OF ACCRETION TO THE
!       BED PER UNIT AREA
      TYPE(BIEF_OBJ), TARGET :: GAMC
!
!     COEFFICIENT QUANTIFYING THE RATE OF ACCRETION TO THE
!       BED PER UNIT AREA
      TYPE(BIEF_OBJ), TARGET :: GAMA
!
! ICE PROPERTY ON THE NODES/POINTS  ICE CONCENTRATION,THICKNESS,VELOCITY
!      TYPE(BIEF_OBJ), TARGET :: DTHIFEM
!
!      TOTAL WATER DISCHARGE
!      TYPE(BIEF_OBJ), TARGET :: QX,QY
!
!      DISCHARGE IN THE ICE LAYER
!      TYPE(BIEF_OBJ), TARGET :: UQX,UQY
!
!      TYPE(BIEF_OBJ), TARGET :: TMICE
!
!     SOLID ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THIFEMS
!
!     ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THIFEM
!
!     ICE PROPERTY ON THE NODES/POINTS  ICE CONCENTRATION,THICKNESS,VELOCITY
      TYPE(BIEF_OBJ), TARGET :: DTHIFEM
!     TOTAL WATER DISCHARGE
      TYPE(BIEF_OBJ), TARGET :: QX,QY
!      ICE VELOCITY
      TYPE(BIEF_OBJ), TARGET :: UICE,VICE,ZICE
!      DISCHARGE IN THE ICE LAYER
      TYPE(BIEF_OBJ), TARGET :: UQX,UQY
!     WATER VELOCITY MAGNITUDE
      TYPE(BIEF_OBJ), TARGET :: ZWAT
!     RELATIVE VELOCITY BETWEEN ICE - WATER
      TYPE(BIEF_OBJ), TARGET :: ZWI
      TYPE(BIEF_OBJ), TARGET :: TMICE,CNIEND
!     BED AND ICE INFLUENCING DEPTH
      TYPE(BIEF_OBJ), TARGET :: HBED,HICE
!     UNDERCOVER TRANSPORT NODES
      TYPE(BIEF_OBJ), TARGET :: IFUND
!     UNDERCOVER ICE TRANSPORT CAPACITY
      TYPE(BIEF_OBJ), TARGET :: UNQIC0,UNQIC
!     UNDERCOVER ICE TRANSPORT RATE
      TYPE(BIEF_OBJ), TARGET :: UNQP0,UNQP
!     UNDERCOVER ICE ADAPTATION LENGTH
      TYPE(BIEF_OBJ), TARGET :: UNFORML
!     UNDERCOVER ICE TRANSPORT DIRECTION
      TYPE(BIEF_OBJ), TARGET :: UNUXP,UNUYP
!     UNDERCOVER ICE TRANSPORT THICKNESS
      TYPE(BIEF_OBJ), TARGET :: UNFS
!     UNDERCOVER ICE VELOCITY
      TYPE(BIEF_OBJ), TARGET :: UNVP
!     ICE-WATER FRICTION
      TYPE(BIEF_OBJ), TARGET :: TIOUT
!     ANCHOR ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THUN
!
!     CRUST ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: TISFEM,TIPFEM
!     MASS OF SOLID AND FRAZIL LAYER, RESPECTIVELY
      TYPE(BIEF_OBJ), TARGET :: PMS,PMF
!     MASS OF CRUST
      TYPE(BIEF_OBJ), TARGET :: PMCRUST
!     ICE PARCEL AREA
      TYPE(BIEF_OBJ), TARGET :: AREAP
!     TOTAL ICE MASS
      TYPE(BIEF_OBJ), TARGET :: PM
!     THICKNESS OF SOLID AND FRAZIL LAYER, RESPECTIVELY
      TYPE(BIEF_OBJ), TARGET :: THIPS,THIPF
!     INITIAL ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: THI0P
!     LOCAL COORDINATE OF MESH
      TYPE(BIEF_OBJ), TARGET :: XFEM,YFEM
!     X,Y COORDINATE OF ICE PARCEL AT TN
      TYPE(BIEF_OBJ), TARGET :: XP0,YP0
!     VELOCITY OF ICE PARCEL AT TN
      TYPE(BIEF_OBJ), TARGET :: UPX0,UPY0
!     X,Y COORDINATE OF ICE PARCEL AT TN+1
      TYPE(BIEF_OBJ), TARGET :: XP,YP
!     VELOCITY OF ICE PARCEL AT TN + 1
      TYPE(BIEF_OBJ), TARGET :: UPX,UPY
!     MASS DENSITY OF ICE PARCEL AT TN AND TN+1
      TYPE(BIEF_OBJ), TARGET :: UM0,UM
!     WATER DEPTH UNDER THE ICE PARCEL
      TYPE(BIEF_OBJ), TARGET :: HHPK
!
      TYPE(BIEF_OBJ), TARGET :: VIC
!     ICE PARCEL SIZE TN+1
      TYPE(BIEF_OBJ), TARGET :: HPX,HPY
!     ICE PARCEL SIZE TN
      TYPE(BIEF_OBJ), TARGET :: HPX0,HPY0
!     GRADIENT TERMS
      TYPE(BIEF_OBJ), TARGET :: DUDX,DUDY,DVDX,DVDY,DUDXT,
     &                          DUDYT,DVDXT,DVDYT
!     INTERNAL STRESS
      TYPE(BIEF_OBJ), TARGET :: SIGXX,SIGYY,SIGXY
!     PRESSURE
      TYPE(BIEF_OBJ), TARGET :: PR
!     INTERNAL STRESS
      TYPE(BIEF_OBJ), TARGET :: STRFX,STRFY
!     TIME STEP FOR ICE DYNAMICS
      TYPE(BIEF_OBJ), TARGET :: TP,TPG
!     ICE PARCEL CONCENTRATION
      TYPE(BIEF_OBJ), TARGET :: ANP
!     ICE PARCEL THICKNESS
      TYPE(BIEF_OBJ), TARGET :: THIP
!     THE BOTTOM ELEVATION OF THE ICE PARCEL
      TYPE(BIEF_OBJ), TARGET :: BOTTOM_P
!     WATER SURFACE ELEVATION OF THE PARCEL
      TYPE(BIEF_OBJ), TARGET :: ETA_P
!     WATER VELOCITY UNDER THE ICE PARCEL
      TYPE(BIEF_OBJ), TARGET :: UPXW,UPYW
!     BOUNDARY ICE CONCENTRATION
!      TYPE(BIEF_OBJ), TARGET :: ANB
!     SURFACE ICE OR ICE UNDER THE COVER
      TYPE(BIEF_OBJ), TARGET :: ICV
!     X,Y COORDINATE TO ISSUE THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: XBFLX,YBFLX
!
!     ICE CONCENTRATION  AT THE BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: ANFLX
!
!     DISTANCE TO ISSUE THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: DLFLX
!
!     TIME TO ISSUE THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: TR
!
!     DIRECTION OF THE ICE BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: SLPB
!
!     WATER VELOCITY AT THE ICE BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: VWXFLX,VWYFLX
!
!     DIRECTION OF THE SOLID BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: PAPHA1,PAPHA2
!
!     DISTANCE BETWEEN ICE PARCEL AND SOLID BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: PARDIS
!
!     DIRECTION OF THE ICE BOOM
!      TYPE(BIEF_OBJ), TARGET :: PAPHABM1,PAPHABM2
!
!     DISTANCE BETWEEN ICE APARCEL AND ICE BOOM
!      TYPE(BIEF_OBJ), TARGET :: PARDISBM
!
!     DIRECTION OF THE ICE BOOM (SIN,COS)
!      TYPE(BIEF_OBJ), TARGET :: ALPHA11,ALPHA12
!
!     DISTANCE BETWEEN ICE PARCEL AND ICE BOOM
!      TYPE(BIEF_OBJ), TARGET :: PARDS1
!
!     STRESS STATE
      TYPE(BIEF_OBJ), TARGET :: KSTRESSSTATE
!     GRADIENT
      TYPE(BIEF_OBJ), TARGET :: DUDYDVDXT
!     HYDROSTATIC PRESSURE
      TYPE(BIEF_OBJ), TARGET :: HYDROPR
!     KERNEL
      TYPE(BIEF_OBJ), TARGET :: PW
!     KERNEL DERIVATIVE
      TYPE(BIEF_OBJ), TARGET :: PDWX,PDWY
!     ARTIFICIAL VISCOSITY
      TYPE(BIEF_OBJ), TARGET :: AVISC
!     ICE BOOM COORDINATE
!      TYPE(BIEF_OBJ), TARGET :: XBM,YBM
!
!     ICE BOOM SPAN COORDINATE
!      TYPE(BIEF_OBJ), TARGET :: XBMSPAN,YBMSPAN
!
!     FORCE PER UNIT LENGTH IN SPAN J
!      TYPE(BIEF_OBJ), TARGET :: ASIGNP
!
!     ICE BOOM FLOAT OR SUBMERGE
!      TYPE(BIEF_OBJ), TARGET :: FRNUM1
!
!     ICE THICKNESS AT THE ICE BOOM J
!      TYPE(BIEF_OBJ), TARGET :: THISPAN
!
!     CRITICAL SUBMERGENCE LINE LOAD OF BOOM
!      TYPE(BIEF_OBJ), TARGET :: BMLINELD
!
!     CRITICAL ICE THICKNESS ABOVE SUBMERGED BOOM FOR RE-EMERGENCE
!      TYPE(BIEF_OBJ), TARGET :: THIEMERG
!
!     BOTTOM ELEVATION OF THE GATE
!      TYPE(BIEF_OBJ), TARGET :: GATE
!
!     BUOYANT FORCE OF THE ICE BOOM WHEN IT IS SUBMERGED
!      TYPE(BIEF_OBJ), TARGET :: BMBUOY
!
!     FRICTION COEFFICIENT BETWEEN THE ICE BOOM AND THE BOTTOM OF THE ICE
!      TYPE(BIEF_OBJ), TARGET :: BMFRIC
!
!
!
!
!-----------------------------------------------------------------------
!
!       2) INTEGERS
!     FRAZIL CLOGGING INDEX
      TYPE(BIEF_OBJ), TARGET :: LIFCG
!     ICE ISLAND INDEX
      TYPE(BIEF_OBJ), TARGET :: JAMFEM
!     BORDER ICE INDEX
      TYPE(BIEF_OBJ), TARGET :: ISBORDER
!     ICE BANK INDEX
      TYPE(BIEF_OBJ), TARGET :: ISBANK
!     ICE TYPE INDEX
      TYPE(BIEF_OBJ), TARGET :: ICEREGION
!   FOR OUTPUT ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: DHIOUT
!     ELEMENT NUMBER OF PARCEL LOCATION AT TN AND TN+1
      TYPE(BIEF_OBJ), TARGET :: NPARELM,NPARELM0
!     BOUNDARY TYPE FOR ICE PARCEL
      TYPE(BIEF_OBJ), TARGET :: NPOUT
!     SORT ORDER OF ICE PARCEL
      TYPE(BIEF_OBJ), TARGET :: NSORT
!     THICKNESS OF POROUS ICE
      TYPE(BIEF_OBJ), TARGET :: TIPP
!     THICKNESS OF SOLID ICE
      TYPE(BIEF_OBJ), TARGET :: TISP
!     ICE PARCEL POROSITY
      TYPE(BIEF_OBJ), TARGET :: EP
!     ICE PARCEL POROSITY
      TYPE(BIEF_OBJ), TARGET :: ICEORGP
!     ICE PARCEL POROSITY
      TYPE(BIEF_OBJ), TARGET :: ICETYPEP
!     ICE STOPPAGE
      TYPE(BIEF_OBJ), TARGET :: IDELTA
!     NUMBER OF NEIGHBORING ICE PARCELS
      TYPE(BIEF_OBJ), TARGET :: NXTP
!     STATIC ICE COVER BEFOR BREAKUP
      TYPE(BIEF_OBJ), TARGET :: IDV
!     PARCEL'S NUMBER IN THE IMAGE PARCEL LIST
      TYPE(BIEF_OBJ), TARGET :: NAPHA
!      TOTAL NUMBER OF NEIGHBORING ICE PARCELS
      TYPE(BIEF_OBJ), TARGET :: INTN
!     PARCEL'S NUMBER OF BOOM IMAGE
!      TYPE(BIEF_OBJ), TARGET :: NAPHABM
!
!     TYPE OF ICE BOOM PARCEL IMAGE
      TYPE(BIEF_OBJ), TARGET :: IPBOOM
!     SPAN OF THE ICE BOOM
      TYPE(BIEF_OBJ), TARGET :: JSPAN
!     FINITE ELEMENT NODE ORIENTATION
      TYPE(BIEF_OBJ), TARGET :: ALAFAN
!     FINITE ELEMENT ZONE NUMBER
      TYPE(BIEF_OBJ), TARGET :: IRDIV
!!     STARTING AND ENDING POINTS OF THE ICE FLUX BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: KPBD,KPBD1
!
!     THE NODE NUMBERS OF EACH ICE FLUX BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: NPBD
!
!     NUMBER OF ICE BOOMS
!      TYPE(BIEF_OBJ), TARGET :: NBM
!
!     NUMBER OF ICE BOOM SPANS
!      TYPE(BIEF_OBJ), TARGET :: NBMSPAN
!
!     ICE BOOM TYPES
!      TYPE(BIEF_OBJ), TARGET :: BOOMTYPE
!
!-----------------------------------------------------------------------
!
!     MAXIMUM NUMBER OF OUTPUT VARIABLES
!
      INTEGER, PARAMETER :: MAXICEVAR = 50

!     STARTING AND ENDING POINTS OF THE ICE FLUX BOUNDARY
      INTEGER, ALLOCATABLE :: KPBD(:),KPBD1(:)

!     THE NODE NUMBERS OF EACH ICE FLUX BOUNDARY
      INTEGER, ALLOCATABLE :: NPBD(:)

!     REFERENCE NODE TO TRACK WATER LEVEL CHANGE FOR BREAKUP
      INTEGER, ALLOCATABLE :: IREFNOD(:)

!     SWITCH TO USE ICE THICKNESS AS CRITICAL WATER LEVEL CHANGE VALUE
      INTEGER, ALLOCATABLE :: IBRKDTI(:)

!     SWITCH TO USE MINIMUM WATER LEVEL CHANGE VALUE
      INTEGER, ALLOCATABLE :: IBRKWSE(:)

!     NUMBER OF DOWNSTREAM ZONES CONTROLLING ICE COVER BREAKUP
      INTEGER, ALLOCATABLE :: NBKZON(:)

!     DOWNSTREAM ZONE CONTROLLONG ICE COVER BREAKUP
      INTEGER, ALLOCATABLE :: IBKRCH(:)

!     ZONE TO CHECK BREAKUP
      INTEGER, ALLOCATABLE :: IBRZON(:)

!     DOWNSTREAM ZONE
      INTEGER, ALLOCATABLE :: IBKCTR(:,:)

!     FEM ELEMENT AND NODE INFORMATION
      INTEGER, ALLOCATABLE :: MEGRID(:,:),NDGRID(:,:),LINKED(:,:)

!     FINITE ELEMENT CODE
      INTEGER, ALLOCATABLE :: NCODE(:)

!     FINITE ELEMENT CODE
      INTEGER, ALLOCATABLE :: NECODE(:)

!     FINITE ELEMENT BOUNDARY CODE
      INTEGER, ALLOCATABLE :: NCBDY(:),NSTAR(:),NEND(:)

!     FINITE ELEMENT NODES IN COUNTER CLOSCKWISE ORDER
      INTEGER, ALLOCATABLE :: NODE1(:),NODE2(:),NODE3(:)

!     SOLID BOUNDARY CONNECTIVITY
      INTEGER, ALLOCATABLE :: NODELB(:)

!     OPEN BOUNDARY CONNECTIVITY
      INTEGER, ALLOCATABLE :: NODEOB(:)

!     SOLID BOUNDARY NODE NUMBER
      INTEGER, ALLOCATABLE :: KLB(:),KLE(:)

!     OPEN BOUNDARY NODE NUMBER
      INTEGER, ALLOCATABLE :: KOB(:),KOE(:)

!     UNDERCOVER BOUNDARY NUMBER AND NODE NUMBER
      INTEGER, ALLOCATABLE :: KUNPD(:),NUNQP(:)

!     IMAGE ELEMENT
      INTEGER, ALLOCATABLE :: IMGELM(:,:)

      !PARCEL'S NUMBER OF BOOM IMAGE
      INTEGER, ALLOCATABLE ::NAPHABM(:,:)

!     TRASH RACK CROSS SECTION NODES
      INTEGER, ALLOCATABLE :: NITKCS(:),NIFZCS(:),NCGNO(:),NFZNO(:)

!!    NUMDER OF PARCELS IN EACH ELEMENT
!      INTEGER, ALLOCATABLE :: NPARSINEL(:)
!
!     NUMBER OF FRAZIL INPUT BOUNDARY
!
!      INTEGER NTWBC
!
!      INTEGER NBM
!
!     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!
!
      INTEGER NTWBC

      !     # IWEATHER (=1, COMPLETE WEATHER DATA; =0, AIR TEMPERATURE ONLY))

      INTEGER IWEATYPE

!     NUMBER OF INTAKES
      INTEGER NITK

!     SWTICH FOR FRAZIL CLOGGING
      INTEGER NCLOG

      INTEGER, PARAMETER :: MAXFRO = 50

!     MAXIMUM NODE NUMBER, ELEMENT NUMBER
      INTEGER MAXNOD,MAXEL

!     MAXIMUM NEIGHBORING NODE NUMBER
      INTEGER MAXLNK

!     MAXIMUM ICE PARCEL NUMBER
      INTEGER MAXPAR

!     MAXIMUM TOTAL NEIGHBORING PARCEL NUMBER
      INTEGER MAXKRN

!      NUNBER OF ICE BOOM
      INTEGER NBM

!      MAXIMUM NUNBER OF ICE BOOM
      INTEGER MAXBM

!      MAXIMUM NUNBER OF ICE BOOM SPAN
      INTEGER MAXBMSP

!      MAXIMUM NUMBER OF ICE BOUNDARY SEGMENT
      INTEGER MAXGDB

!      MAXIMUM BOUNDARY PARCEL NUMBER
      INTEGER MAXNBP

!     PARCEL SEARCH XMIN,MAX,YMIN,YMAX
      INTEGER MINGDX,MAXGDX,MINGDY,MAXGDY

!     NUMBER OF ICE BOOM SPANS
      INTEGER NBMSP

!     ICE BOOM TYPES
      INTEGER BMTYPE

!      NUMBER OF SLOT TO ISSUE ICE
      INTEGER ITBDF

!      MAXIMUM NUMBER OF BREAKUP REACHES
      INTEGER MAXBRK

!      NUMBER OF BREAKUP REACHES
      INTEGER NCOV

!      NUMBER OF SOLID BOUNDARY
      INTEGER NMLBN

!      NUMBER OF OPEN BOUNDARY
      INTEGER NMOBN

!      MAXIMUM NUMBER OF SOLID BOUNDARY
      INTEGER MAXSDB

!      MAXIMUM NUMBER OF OPEN BOUNDARY
      INTEGER MAXOPB

!      NUMBER OF UNDERCOVER BOUNDARY
      INTEGER NUQSEC

!     TYEP OF UNDERCOVER BOUDNARY CONDITION
      INTEGER IUQBC

!     COUNTER FOR UNDERCOVER BOUNDARY CONDITION
      INTEGER IUNDT

      INTEGER ITMAX
      !     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!      NUMBER OF ICE BOUNDARY
      INTEGER MSBD

!      ICE CONCENTRATION BE SPECIFIED
      INTEGER IQBJB

!      NUMBER OF SOLID BOUNDARY
      INTEGER NLB

!     NUMBER OF OPEN BOUNDARY
      INTEGER NOB

!     NUMBER OF TIMESTEP FOR ICEDYNAMICS
      INTEGER ITICE

!     NUMBER OF TIMESTEP FOR UNDERCOVER
      INTEGER IUND

      INTEGER NTBN,NHBN,NQBN,N0BN,NHTN,NFBN,NQB1,NQ0,NQ01,
     &  NEL,NSBN

!     NUMBER OF PARCEL IN THE DOMAIN
      INTEGER NPARIN

!     NUMBER OF PARCEL MOVING OUT OF THE DOMAIN
      INTEGER NPAROUT

!     DELETE THE BAD PARCELS
      INTEGER NBADPARCELS

!     TOTAL NUMBER OF PARCELS
      INTEGER NTOTALPARCELS

!     FILE NUMBER FOR UNDERCOVER BOUNDARY FILE
      INTEGER IUDC

!     FILE NUMBER FOR ICE BOOM FILE
      INTEGER INBM

!     FILE NUMBER FOR ICE BOOM FORCE FILE
      INTEGER IBMF

!     FILE NUMBER FOR BREAK UP FILE
      INTEGER IBRK

!     FILE NUMBER FOR ICE CONDITION ON FEM NODE FILE
      INTEGER IHDW0

!     FILE NUMBER FOR FRAZIL DEPOSITION AND ENTRAINMENT
      INTEGER IFRZ

!     FILE NUMBER FOR TRASH TRACK AND CROSS SECTIONS
      INTEGER ICSG

!     ICE FLUX TIME FRAME
      INTEGER KFLXI

!     MAXIMUM STEPS TO CHANGE THE ICE THICKNESS FOR HYDRODYNAMICS
      INTEGER ITHIMAX

!     STEPS TO CHANGE THE ICE THICKNESS FOR HYDRODYNAMICS
      INTEGER ITHIUP

      INTEGER KPRT
      INTEGER KDMPH
      INTEGER KDMPI
      INTEGER KDMPHI

      INTEGER KWND
      INTEGER KELV,KFLX,
     &  KHDW,KHDI,KHOT,KSTR,KTHR,IRND,ISEED
!          ! UPDATE BOUNDARY AND OUTPUT
     & JOBFLX,NSEC,NDISC,NELEV,ISTRT,
     & IHDW,IHOT0,IHOT,ISTR0,ISTR,ILNK,
     & IPRO,IPLT,ICLG,IQBD

!     NUMBER OF ICE PARCELS
      INTEGER KNP

!     STEPS TO CHECK BREAKUP
      INTEGER NBKDTM

!     NUMBER OF REACHES FOR BREAKUP
      INTEGER NRCH

!     SEED FOR RANDOM NUMBER
      INTEGER ISEED

!     ! INDEX FOR DISCHARGE USED FOR FRAZIL ACCRETION
!      INTEGER, PARAMETER :: KCGQ = 1
!
!
!
!
!-----------------------------------------------------------------------
!
!       3) LOGICAL
!
!     WITH ICEDYNAMICS CALCULATION
      LOGICAL ICEDYNAMICS
!

!      WITH THERMAL CALCULATION
      LOGICAL ITHERMOICESWITH
!
!     LINK FILE
!
      LOGICAL ILINKSWITCH
!
!     IF YES, MASS-BALANCE
!
!     ITHERMOSWITCH:
!        = 0, NO THERMAL CALCULATION
!        = 1, WITH THERMAL CALCULATION
      LOGICAL ITHERMOSWITCH
!
!     IUNDERCOVERSWITCH:
!        = 0, NO UNDER COVER TRANSPORT CALCULATION
!        = 1, WITH UNDERCOVER TRANSPORT CALCULATION
      LOGICAL IUNDERCOVERSWITCH
!
!     IBREAKUPSWITCH
!        = 0, NO BREAKUP CALCULATION
!        = 1, WITH BREAKUP CALCULATION
      LOGICAL IBREAKUPSWITCH
!
!     IF YES, MASS-BALANCE
      LOGICAL ICEBILMAS
!
!     IF YES, VALIDATION
      LOGICAL ICEVALID
!
!     STEADY HYDRODYNAMICS
      LOGICAL  PERMA
!
!     IF TEMPERATURE IS VARIABLE
!
      LOGICAL YATEMP

!      IF YES, FRAZIL CLOGGING

      LOGICAL IFCLOGSWITCH

!      IF YES, TECPLOT OUTPUT

      LOGICAL IOUTPUT

!      IF YES, ICE INPUT

      LOGICAL ICIPUT
!
!-----------------------------------------------------------------------
!
!       4) REALS
!
!-----------------------------------------------------------------------

      DOUBLE PRECISION RHOW,RHOICE,RHOAIR,ROI
!  ICE LATENT HEAT
!      DOUBLE PRECISION XLATEN    !       => MOVED TO KHIONE UNDER LH_ICE

      !  CLOUDINESS
      DOUBLE PRECISION CC

!     GEOGRAPHIC LATITUDE, + FOR NORTH, - FOR SOUTH
      DOUBLE PRECISION PHID

!     HEIGHT THE WIND DATA IS MEASUR ED(M)
      DOUBLE PRECISION Z1

!     ELEVATION MEASURED FROM SEA  LEVEL(M)
      DOUBLE PRECISION ZH

!--------------------------------------------------------------
!  GROUP FOR SIMULATING WATER TEMPERATURE AND THERMAL GROWTH AND DECAY OF ICE

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON WATER-AIR SURFACE
      DOUBLE PRECISION HWA

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON ICE-AIR SURFACE
      DOUBLE PRECISION HIA

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON ICE-AIR SURFACE
      DOUBLE PRECISION ALP

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON WATER-AIR SURFACE
      DOUBLE PRECISION ALPW
!
!     CONSTANT FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR TURBULENT FLOW
      DOUBLE PRECISION CWI1
!
!     CONSTANT FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR SUPERCOOLED TURBULENT FLOW
      DOUBLE PRECISION CIW1
!
!     NUSSELT NUMBER FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR LAMINAR FLOW
      DOUBLE PRECISION ATA

!     HEAT TRANSFER COEFFICIENT FROM WATER TO ICE
      DOUBLE PRECISION CWI
!
!     KINEMATIC VISCOSITY OF WATER
      DOUBLE PRECISION XNU

!------------------------------------------------------------------------
!   GROUP FOR SIMULATING BORDER ICE FORMATION
!
!     CRITICAL WATER SURFACE TEMPERATURE FOR BORDER ICE FORMATION
      DOUBLE PRECISION TC
!
!     CRITICAL VELOCITY ABOVE WHICH SKIM ICE WILL NOT FORM (M/S)
      DOUBLE PRECISION VCRSKM
!
!     CHANNEL WIDTH FOR THE COMPUTATION OF SURFACE WATER TEMPERATURE
      DOUBLE PRECISION BCH
!
!     MAXIMUM CONCENTRATION FOR BORDER ICE FORMATION
!      DOUBLE PRECISION ANMAXBORDER
!
!----------------------------------------------------------------------------
! GROUP FOR SKIM ICE SIMULATION
!
!     MAXIMUM CONCENTRATION FOR SKIM ICE RUN
!      DOUBLE PRECISION ANMAXSKIM                 => REPLACED BY ANFEM0
!
!--------------------------------------------------------------------------
! GROUP FOR MASS EXCHANGE BETWEEN SUSPENDED LAYER, SURFACE LAYER AND ANCHOR ICE
!
!     INITIAL THICKNESS OF FRAZIL PART OF ICE FLOES(M)
      DOUBLE PRECISION HF0
!
!     MAXIMUM CONCENTRATION OF FRAZIL ICE PARCEL FROM SUSPENDED LAYER TO SURFACE LAYER
      DOUBLE PRECISION ANMAXFRA
!
!     MINIMUM CONCENTRATION OF FRAZIL ICE PARCEL FROM SUSPENDED LAYER TO SURFACE LAYER
      DOUBLE PRECISION ANMINFRA

!     POROSITY OF SURFACE ICE
      DOUBLE PRECISION EF

!     POROSITY OF FRAZIL ICE
      DOUBLE PRECISION EF0

!     VERTICAL BAR LENGTH
      DOUBLE PRECISION HBAR
!-----------------------------------------------------------------------------------
! GROUP FOR SUPERCOOLING SIMULATION
!
!     NUCLEATION TEMPERATURE(OC)
      DOUBLE PRECISION TUN
!
!     DISPERSION LONGITUDINALE,TRANSVERSALE
      DOUBLE PRECISION LDISP,TDISP
!-------------------------------------------------------------------------------
!  GROUP FOR UNDERCOVER TRANSPORT SIMULATION
!
!     NOMINAL DIAMETER OF ICE PARTICLES(M)
      DOUBLE PRECISION UNPSIZE
!
!     CRITICAL FLOW STRENGTH, BELOW WHICH THERE IS NO ICE TRANSPORT
      DOUBLE PRECISION UNTHETAC
!
!     MAXIMUM CONCENTRATION OF UNDERCOVER LOAD
      DOUBLE PRECISION UNMAXANP
!
!     THE RATIO OF UNCOVER LOAD TRANSPORTATION VELOCITY TO FLOW VELOCITY
      DOUBLE PRECISION UNALPHAV

!     BUOYANT VELOICTY OF UNDERCOVER ICE
      DOUBLE PRECISION VBUN

!     UNDERCOVER TRANSPORT ADAPTATION LENGTH
      DOUBLE PRECISION ADPL
!-------------------------------------------------------------------------------
!  GROUP FOR ICE COVER FORMATION
!
!     ICE PARCEL STOPPAGE CRITERION
      DOUBLE PRECISION STPV
!
!     CRITICAL FROUDE NUMBER FOR ICE PARCEL TO SUBMERGE
      DOUBLE PRECISION CRIFR
!
!     EROSION VELOCITY OF ICE PARCELS
      DOUBLE PRECISION UEROS
!
!     CRITICAL VELOCITY FOR FREEZING CALCULATION
      DOUBLE PRECISION VCRFRZ
!
!     COMPRESSIVE STRENGTH OF THE ICE COVER
      DOUBLE PRECISION STRENGTH
!
!     INITIAL AND CURRENT WIDTH FOR VERTICAL BARS
      DOUBLE PRECISION WFV0,WFV1
!
!     INITIAL AND CURRENT WIDTH FOR TRANSVERSE BARS
      DOUBLE PRECISION WFT0,WFT1
!
!     INITIAL AND CURRENT WIDTH FOR VERTICAL BARS
      DOUBLE PRECISION WFV0DW,WFV1DW
!
!     INITIAL AND CURRENT WIDTH FOR TRANSVERSE BARS
      DOUBLE PRECISION WFT0DW,WFT1DW
!
!
      DOUBLE PRECISION TIME,GRAVT,CORIO,PI,SQPI
      DOUBLE PRECISION  RHO,RHOI,RADDIG,RHOS
!
!     PARAMETERS FOR ICE
!     SUB-GRID SIZE
      DOUBLE PRECISION SGRD

!     GEOMETRY MAX & MIN
      DOUBLE PRECISION XMIN,YMIN,XMAX,YMAX,XGMIN,YGMIN

!     INITIAL ICE PARCEL CONCENTRATION
      DOUBLE PRECISION AN0

!     INITIAL FRAZIL ICE THICKNESS
      DOUBLE PRECISION THI0F

!     INITIAL SIZE OF ICE PARCEL
      DOUBLE PRECISION HPI0
!
!     ICE TIME STEP
      DOUBLE PRECISION TIMICE
!
!     A MINIMUM VALUE
      DOUBLE PRECISION VSM
!
!     NUMBER OF ICE PARCELS
!     DOUBLE PRECISION KNP
!
!     ICE PARCEL MASS
      DOUBLE PRECISION PM1
!
      DOUBLE PRECISION ANGLE   ! MAY NOT NEED;   WIND ANGLE
!
      DOUBLE PRECISION REFEL   ! MAY NOT NEED; REFERENCE LEVEL FOR HYDRO
!
      DOUBLE PRECISION OPTIM  ! MAY NOT NEED; OPTIMAL TIME STEP FOR HYDRO
!
!     ICE MASS DENSITY AND ICE MASS AT TN
      DOUBLE PRECISION UMI0,PMI0,PMI0F

!     FRICTION COEFFICIENT BETWEEN ICE-RIVERBANK; ICE-RIVERBED
      DOUBLE PRECISION FRIC1,FRIC2
!
!     AIR-ICE DRAG COEFFICIENT
      DOUBLE PRECISION WDCA

!     ICE INTERNAL FRICTION ANGLE
      DOUBLE PRECISION PHI
!
!     EMPIRICAL CONSTANT
      DOUBLE PRECISION PJ
!
!     MAX WATER-ICE DRAG COEFFICIENT
      DOUBLE PRECISION CWMAX

!     BOLTZMANN CONSTANT (WM-2K-4)
      DOUBLE PRECISION SGMA

!     SPECIFIC HEAT OF WATER
      DOUBLE PRECISION CP

!     SPECIFIC HEAT OF ICE
      DOUBLE PRECISION CI

!     TIME FOR ICE DYNAMICS
      DOUBLE PRECISION DELTMI,TINTVL,TIMICE0
      DOUBLE PRECISION TMN
      DOUBLE PRECISION ENDTIME

!      UNDERCOVER TIME STEP
      DOUBLE PRECISION UNDT

!     STARTING TIME OF ICE DYNAMICS
      DOUBLE PRECISION TICEBG,TICE0

!     TIME FOR UNDERCOVER
      DOUBLE PRECISION TUNBG,DELTMU,TINUN

!     BOOM CURTAIN DEPTH
      DOUBLE PRECISION DWALL

!     TIME INTERVAL FOR OUTPUT ICE FORCE ON THE BOOM
      DOUBLE PRECISION DTBMF

      ! WEATHER TIME
      DOUBLE PRECISION TIMA0,TIMA1,TAIR0,TAIR1


!     VARIABLES FOR BOUNDARY CONDITIONS AND NODAL INFORMATION FOR
!     HYDRODYNAMICS MAY NOT BE NEEDED
      DOUBLE PRECISION SINBN,COSBN,HB,
     & QB,STEMP,CTEMP,DISCH,DISCHU,
     & WNDTIME,PRTTIME,DMPTIMH,DMPTIMI,
     & FAC,QBT,QBTI,QIN,XBGN,YBGN,XEND,YEND

!!    BOUNDARY ICE CONCENTRATION
      DOUBLE PRECISION, ALLOCATABLE :: ANB(:),QIB(:)

!     TIME SERIES OF ICE FLUX
      DOUBLE PRECISION, ALLOCATABLE :: FLXITM(:)

!     X,Y COORDINATE TO ISSUE THE ICE PARCEL
      DOUBLE PRECISION, ALLOCATABLE :: XBFLX(:),YBFLX(:)

!     DISTANCE TO ISSUE THE ICE PARCEL
      DOUBLE PRECISION, ALLOCATABLE :: DLFLX(:)

!     TIME TO ISSUE THE ICE PARCEL
      DOUBLE PRECISION, ALLOCATABLE :: TR(:)

!     DIRECTION OF THE ICE BOUNDARY
      DOUBLE PRECISION, ALLOCATABLE :: SLPB(:)

!     ICE CONCENTRATION  AT THE BOUNDARY FOR EACH SLOT
      DOUBLE PRECISION, ALLOCATABLE :: ANFLX(:)

!     ICE BOOM COORDINATE
      DOUBLE PRECISION, ALLOCATABLE :: XBM(:,:),YBM(:,:)

!     ICE BOOM SPAN COORDINATE
      DOUBLE PRECISION, ALLOCATABLE :: XBMSP(:,:),YBMSP(:,:)

!     FORCE PER UNIT LENGTH IN SPAN J
      DOUBLE PRECISION, ALLOCATABLE :: ASIGNP(:)

!     ICE BOOM FLOAT OR SUBMERGE
      DOUBLE PRECISION, ALLOCATABLE :: FRNUM1(:)

!     ICE THICKNESS AT THE ICE BOOM J
      DOUBLE PRECISION, ALLOCATABLE :: THISP(:)

!     CRITICAL SUBMERGENCE LINE LOAD OF BOOM
      DOUBLE PRECISION, ALLOCATABLE :: BMLINELD(:)

!     CRITICAL ICE THICKNESS ABOVE SUBMERGED BOOM FOR RE-EMERGENCE
      DOUBLE PRECISION, ALLOCATABLE :: THIEMERG(:)

!     BOTTOM ELEVATION OF THE GATE
      DOUBLE PRECISION, ALLOCATABLE :: GATE(:)

!     BUOYANT FORCE OF THE ICE BOOM WHEN IT IS SUBMERGED
      DOUBLE PRECISION, ALLOCATABLE :: BMBUOY(:)

!     FRICTION COEFFICIENT BETWEEN THE ICE BOOM AND THE BOTTOM OF THE ICE
      DOUBLE PRECISION, ALLOCATABLE :: BMFRIC(:)

!     DIRECTION OF THE SOLID BOUNDARY
      DOUBLE PRECISION, ALLOCATABLE :: PAPHA1(:),PAPHA2(:)

!     DISTANCE BETWEEN ICE PARCEL AND SOLID BOUNDARY
      DOUBLE PRECISION, ALLOCATABLE :: PARDIS(:)

!     DIRECTION OF THE ICE BOOM
      DOUBLE PRECISION, ALLOCATABLE :: PAPHABM1(:),PAPHABM2(:)

!     DISTANCE BETWEEN ICE APARCEL AND ICE BOOM
      DOUBLE PRECISION, ALLOCATABLE :: PARDISBM(:)

!!     DIRECTION OF THE ICE BOOM (SIN,COS)
!      DOUBLE PRECISION, ALLOCATABLE :: ALPHA11(:),ALPHA12(:)

!!     DISTANCE BETWEEN ICE PARCEL AND ICE BOOM
!      DOUBLE PRECISION, ALLOCATABLE :: PARDS1(:)

!     TIME FOR ICE COVER BREAKUP
      DOUBLE PRECISION, ALLOCATABLE :: BRKTIM(:)

!     CRITICAL VALUE OF WATER SURFACE ELEVATION AT REFERENCE NODE
      DOUBLE PRECISION, ALLOCATABLE :: BRKWSE(:)

!     CRITICAL VALUE OF WATER SURFACE ELEVATION INCREASE AT REFERENCE NODE
      DOUBLE PRECISION, ALLOCATABLE :: BRKDWSE(:)

!     WATER SURFACE ELEVATON RECORD FOR BREAKUP
      DOUBLE PRECISION, ALLOCATABLE :: WSERD(:,:)

!     INITIAL ICE COVER THICKNESS
      DOUBLE PRECISION, ALLOCATABLE :: COVTI(:)

!     WATER VELOCITY AT THE ICE BOUNDARY
      DOUBLE PRECISION, ALLOCATABLE :: VWXFLX(:),VWYFLX(:)

!      FINITE ELEMENT ORIENTATION AND HEIGHT
      DOUBLE PRECISION, ALLOCATABLE :: ALAFAE(:),ELMHT(:)

!      FINITE ELEMENT MAX EDGE IN X,Y
      DOUBLE PRECISION, ALLOCATABLE :: XMAXH(:),YMAXH(:)

!      FINITE ELEMENT INFORMAITON
      DOUBLE PRECISION, ALLOCATABLE :: A1(:),A2(:),A3(:)
      DOUBLE PRECISION, ALLOCATABLE :: B1(:),B2(:),B3(:)
      DOUBLE PRECISION, ALLOCATABLE :: C1(:),C2(:),C3(:)
      DOUBLE PRECISION, ALLOCATABLE :: CLMP(:)
!     UNDERCOVER BOUNDARY CONDITION
      DOUBLE PRECISION, ALLOCATABLE :: UNDTM(:),UNQBC(:,:)


!      FINITE ELEMENT NODE ORIENTATION
!      DOUBLE PRECISION, ALLOCATABLE :: ALAFAN(:)




!-----------
!--ARRAYS ADDED BY SU FOR PARCEL SEARCH
!      COMMON /ARRY2D1/ MEGRID(MINGDX:MAXGDX,MINGDY:MAXGDY)
!      COMMON /ARRY2D2/ NDGRID(MINGDX:MAXGDX,MINGDY:MAXGDY)
!      COMMON /LINKEND/ LINKED(10,MAXNOD)
!      COMMON /LANDE/ NECODE(MAXEL),NSTAR(MAXEL),NEND(MAXEL),
!     &  ELMHT(MAXEL),ALAFAE(MAXEL),ALAFAN(MAXNOD),NODEL(3,MAXEL)
!      COMMON /SORT/ NSORT(MAXPAR)
!----------------

!
!-----------------------------------------------------------------------
!      LINK FILE
      CHARACTER(LEN=50) LNKFILE

!      ICE BOUNDARY FILE
      CHARACTER(LEN=50) IQBFILE

!      ICE BOOM FILE AND BOOM FORCE FILE
      CHARACTER(LEN=50) BMFILE,BFFILE

!      BREAKUP FILE
      CHARACTER(LEN=50) BKFILE

!      UNDERCOVER TRANSPORT FILE
      CHARACTER(LEN=50) UDFILE

!     FRAZIL COEFFICIENTS FILE
      CHARACTER(LEN=50) FZFILE

!     TRASH RACK CROSS SECTION FILE
      CHARACTER(LEN=50) TRFILE

!     FRAZIL CLOGGING OUTPUT FILE
      CHARACTER(LEN=50) CLGFILE

!     EXISTING ICE CONDITION FILE
      CHARACTER(LEN=50) HT0FILE,ST0FILE,HD0FILE

      CHARACTER(LEN=50) CASENAME,GEOFILE,TIMFILE,PRTFILE,
     &  PTMFILE,FLXFILE,ELVFILE,WNDFILE,DSCFILE,
     &  HO0FILE,ERRFILE,STATE,THRFILE,DELFILE,
     &  QNIFILE,QNWFILE,DBMFILE,
     &  LELFILE,NBMFILE,PROFILE,TBCFILE,LINKEFILE,SWIFILE,MCRFILE,
     &  WEAFILE,ICEVOLUMEFILE,NETFILE,COVFILE,PARFILE,
     &  CLGDWFILE,DSCLOC,ELVLOC,DSCILOC

      INTEGER, PARAMETER :: MAX_ICE_FILE = 1000

!      TYPE(BIEF_FILE) :: PLTFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) PLTFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) HDWFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) HOTFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) STRFILE(MAX_ICE_FILE)

!      CHARACTER(LEN=50) HDWFILE(MAX_ICE_FILE)

!      TYPE(BIEF_FILE) :: CASENAME,FNAME,TIMFILE,
!     &  FLXFILE,ELVFILE,DSCFILE,TBCFILE,
!     &  HD0FILE,HDWFILE(1000),HDIFILE(1000),DSCLOC(200),
!     &  ELVLOC(200),IQBFILE,HO0FILE,THRFILE,DELFILE,CLGFILE,
!     &  HOTFILE(1000),ERRFILE,STATE(0:1),STRFILE(1000),
!     &  ST0FILE,QNIFILE,QNWFILE,BMFFILE,DSCILOC(200),
!     &  LELFILE,NBMFILE,PROFILE(1000),LINKEFILE,WEAFILE,
!     &  BRKFILE,SWIFILE,MCRFILE,PARFILE,
!     &  CLGDWFILE
!
!     NAMES OF ICE ARRAYS (GIVEN BY USER)
!
!      CHARACTER(LEN=32) NAMES_ICVAR(MAXVAR)
!
!-----------------------------------------------------------------------
!
!=======================================================================
!
!       5) BLOCKS
!
!-----------------------------------------------------------------------
!
!     BLOCK OF ICE VARIABLES
!
      TYPE(BIEF_OBJ), TARGET :: ICVAR
!
!
!     BLOCK OF WORKING ARRAYS
!
      TYPE(BIEF_OBJ), TARGET :: TB
!
!=======================================================================
!
!       X) POINTERS
!
!-----------------------------------------------------------------------
!
!     DECLARATION OF POINTERS FOR ALIASES TO WORKING VECTORS IN TB
!     TARGETS ARE DEFINED IN POINT_KHIONE.
!
      TYPE(BIEF_OBJ),POINTER :: T1,T2,T3,T4,T5,T6
!
!=======================================================================
!
      SAVE

      END MODULE DECLARATIONS_KHIONE


